dict = set()
word1 = int(input("Enter the number 1: "))
dict.add(word1)
word2 = int(input("Enter the number 2: "))
dict.add(word2)
word3 = int(input("Enter the number 3: "))
dict.add(word3)
word4 = int(input("Enter the number 4: "))
dict.add(word4)
word5 = int(input("Enter the number 5: "))
dict.add(word5)
word6 = int(input("Enter the number 6: "))
dict.add(word6)
word7 = int(input("Enter the number 7: "))
dict.add(word7)
word8 = int(input("Enter the number 8: "))
dict.add(word8)

print(dict)