a = int(input("Enter the marks : "))
if(a>90 and a<100): print("A")
elif(a>80 and a < 90): print("B")
elif(a>70 and a<80): print("C")
elif(a>60 and a<70): print("D")
elif(a>50 and a<60): print("E")
elif(a>40 and a<50): print("F")
else: print("Fail")